name = "cors"
main = "src/index.ts"
compatibility_date = "2022-11-24"

kv_namespaces = [
    { binding = "ANALYTICS", id = "f1054f984d184d1c976d1b69cc6284d5", preview_id = "4daadfc8c22742acab5fb924892f76a9" },
]
